### ISSUE TITLE
Get the type for `history` from the `history` package

### ISSUE THREAD

**Issue by maurogestoso** [mercadona/wrapito#90]
## ✨ Feature proposal
We currently get the type for the `history` object from `RouterProps[history]`. We can do this because `react-router` has `history` as a dependency and it exposes it.

## 🎯 Motivation
We think using the `history` type directly makes more sense and it doesn't add a new dependency (it just becomes explicit)

## 👀 Example
```typescript
import { History } from 'history';
{
    history: History
}
```

**Comment by raulmoyareyes** [comment]
We fixed it in https://github.com/mercadona/wrapito/pull/104
